export const GET_ALL_BLOGS = 'home/GET_ALL_BLOGS';
export const GET_BLOG = 'home/GET_BLOG';
export const TITLE_TEXT_CHANGE = 'home/TITLE_TEXT_CHANGE';
export const DESCRIPTION_TEXT_CHANGE = 'home/DESCRIPTION_TEXT_CHANGE';
export const CREATE_BLOG = 'home/CREATE_BLOG';
export const CREATE_BLOG_FAILED = 'home/CREATE_BLOG_FAILED';
export const CREATE_BLOG_SUCCESSFUL = 'home/CREATE_BLOG_SUCCESSFUL';
export const UPDATING_BLOG = 'home/UPDATING_BLOG';
export const UPDATING_BLOG_FAILED = 'home/UPDATING_BLOG_FAILED';
export const UPDATING_BLOG_SUCCESSFUL = 'home/UPDATING_BLOG_SUCCESSFUL';
export const SAVING_BLOG = 'home/SAVING_EDITED_BLOG';
export const SAVING_BLOG_FAILED = 'home/SAVING_EDITED_BLOG_FAILED';
export const SAVING_BLOG_SUCCESSFUL = 'home/SAVING_EDITED_BLOG_SUCCESSFUL';
export const DELETING_BLOG = 'home/DELETING_BLOG';
export const DELETING_BLOG_FAILED = 'home/DELETING_BLOG_FAILED';
export const DELETING_BLOG_SUCCESSFUL = 'home/DELETING_BLOG_SUCCESSFUL';

